[build]
  command   = "npx nx run finance-angular:build:production"
  publish   = "dist/samples/finance/angular/browser"
  edge_functions = "dist/samples/finance/netlify"

[[edge_functions]]
  path = "/api/chat"
  function = "chat"

[[edge_functions]]
  path = "/api/ingredients"
  function = "ingredients"
