name: Deploy Cloudflare Previews

on:
  push:
    branches:
      - main
      
concurrency:
  group: cloudflare-preview
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PREVIEW_BRANCH: preview-${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install
        run: npm ci

      - name: Build apps for Pages
        run: npx nx run-many -t build --configuration=production -p finance-angular fast-food-angular fast-food-cloudflare smart-home-angular www

      - name: Deploy Finance (preview)
        working-directory: samples/finance/angular
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler pages deploy ../../../dist/samples/finance/angular/browser --project-name="hashbrown-finance" 

      - name: Deploy Smart Home (preview)
        working-directory: samples/smart-home/angular
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler pages deploy ../../../dist/samples/smart-home/angular/browser --project-name="hashbrown-smart-home"

      - name: Deploy Fast Food (preview)
        working-directory: samples/fast-food/angular
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler pages deploy ../../../dist/samples/fast-food/angular/browser --project-name="hashbrown-fast-food" 

      - name: Deploy Docs (preview)
        working-directory: www/analog
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler pages deploy ../../dist/www/analog/analog/public --project-name="hashbrown-www"
