name: Deploy Cloudflare Previews

on:
  push:
    branches:
      - main

concurrency:
  group: cloudflare-preview
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PREVIEW_BRANCH: preview-${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install
        run: npm ci

      - name: Build apps for Pages
        run: npx nx run-many -t build --configuration=production -p finance-angular fast-food-angular fast-food-cloudflare smart-home-angular www

      - name: Deploy Finance (preview)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/samples/finance/angular/browser --project-name="hashbrown-finance"

      - name: Deploy Smart Home (preview)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/samples/smart-home/angular/browser --project-name="hashbrown-smart-home"

      - name: Deploy Fast Food (preview)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/samples/fast-food/angular/browser --project-name="hashbrown-fast-food" --functions="dist/samples/fast-food/cloudflare"

      - name: Deploy Docs (preview)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/www/analog/analog/public --project-name="hashbrown-finance"
